//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolPooch.Service.Resourses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ServiceMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServiceMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GolPooch.Service.Resourses.ServiceMessage", typeof(ServiceMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب کاربری شما مسدود است.
        /// </summary>
        public static string AccountIsBlocked {
            get {
                return ResourceManager.GetString("AccountIsBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمام راندهای قرعه کشی صندوق مورد نظر به پایان رسیده است، لطفا صندوق دیگری را انتخاب کنید..
        /// </summary>
        public static string AllChestRoundHasFinished {
            get {
                return ResourceManager.GetString("AllChestRoundHasFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای ورود به گل یا پوچ کد زیر را وارد نمایید
        ///Code: {code}.
        /// </summary>
        public static string Authentication_GetCode {
            get {
                return ResourceManager.GetString("Authentication_GetCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صندوق قرعه کشی مورد نظر فعال نمی باشد..
        /// </summary>
        public static string ChestNotActive {
            get {
                return ResourceManager.GetString("ChestNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClosedRoundBySystem.
        /// </summary>
        public static string ClosedRoundBySystem {
            get {
                return ResourceManager.GetString("ClosedRoundBySystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompleteProfile.
        /// </summary>
        public static string CompleteProfile {
            get {
                return ResourceManager.GetString("CompleteProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateFirstRoundBySystem.
        /// </summary>
        public static string CreateFirstRoundBySystem {
            get {
                return ResourceManager.GetString("CreateFirstRoundBySystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateNewRoundBySystem.
        /// </summary>
        public static string CreateNewRoundBySystem {
            get {
                return ResourceManager.GetString("CreateNewRoundBySystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد.
        /// </summary>
        public static string DrawChestCode {
            get {
                return ResourceManager.GetString("DrawChestCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رکورد مورد نظر هم اکنون وجود دارد.
        /// </summary>
        public static string DuplicateRecord {
            get {
                return ResourceManager.GetString("DuplicateRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndDrawBySystem.
        /// </summary>
        public static string EndDrawBySystem {
            get {
                return ResourceManager.GetString("EndDrawBySystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات مورد نظر با خطا رو به رو شده است، لطفا مجددا تلاش نمایید..
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطایی در سرور اتفاق افتاده است.
        /// </summary>
        public static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این کد منقضی شده است و معتبر نمی باشد، لطفا مجدد تلاش کنید.
        /// </summary>
        public static string ExpiredPinCode {
            get {
                return ResourceManager.GetString("ExpiredPinCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذخیره فایل ارسالی با خطا رو به رو شده است ویا فایل ارسالی معتبر نمی باشد..
        /// </summary>
        public static string FileNotSaved {
            get {
                return ResourceManager.GetString("FileNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد شانس های انتخابی معتبر نمی باشد ویا تعداد شانس های انتخابی بیشتر از تعداد شانس های باقیمانده شما می باشد..
        /// </summary>
        public static string InvalidChanceCount {
            get {
                return ResourceManager.GetString("InvalidChanceCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صندوق قرعه کشی مورد نظر معتبر نمی باشد ویا کد صندوق ارسالی اشتباه می باشد..
        /// </summary>
        public static string InvalidChest {
            get {
                return ResourceManager.GetString("InvalidChest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ارسالی معتبر نمی باشد..
        /// </summary>
        public static string InvalidId {
            get {
                return ResourceManager.GetString("InvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره موبایل وارد شده صحیح نمی باشد..
        /// </summary>
        public static string InvalidMobileNumber {
            get {
                return ResourceManager.GetString("InvalidMobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوتیفیکیشن مورد نظر وجود ندارد ویا کد ارسالی معتبر نمی باشد..
        /// </summary>
        public static string InvalidNotificationId {
            get {
                return ResourceManager.GetString("InvalidNotificationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پارامترهای ارسالی اشتباه می باشد، لطفا مجدد تلاش کنید..
        /// </summary>
        public static string InvalidParameter {
            get {
                return ResourceManager.GetString("InvalidParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درگاه بانک مورد نظر معتبر نمی باشد ویا کد درگاه ارسالی اشتباه می باشد..
        /// </summary>
        public static string InvalidPaymentGateway {
            get {
                return ResourceManager.GetString("InvalidPaymentGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تراکنش مورد نظر معتبر نمی باشد ویا کد تراکنش ارسالی اشتباه می باشد..
        /// </summary>
        public static string InvalidPaymentTransaction {
            get {
                return ResourceManager.GetString("InvalidPaymentTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد وارد شده صحیح نمی باشد، لطفا کد دریافتی از طریق پیامک را وارد نمایید..
        /// </summary>
        public static string InvalidPinCode {
            get {
                return ResourceManager.GetString("InvalidPinCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محصول مورد نظر معتبر نمی باشد ویا کد محصول ارسالی اشتباه می باشد..
        /// </summary>
        public static string InvalidProductOffer {
            get {
                return ResourceManager.GetString("InvalidProductOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسته مورد نظر وجود ندارد ویا فعال نمی باشد، لطفا مجدد تلاش کنید..
        /// </summary>
        public static string InvalidProductOfferId {
            get {
                return ResourceManager.GetString("InvalidProductOfferId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محصول خریداری شده معتبر نمی باشد ویا کد محصول خریداری شده اشتباه می باشد..
        /// </summary>
        public static string InvalidPurchase {
            get {
                return ResourceManager.GetString("InvalidPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توکن ارسالی معتبر نمی باشد ویا زمان استفاده از رفرش توکن به پایان رسیده است..
        /// </summary>
        public static string InvalidRefreshToken {
            get {
                return ResourceManager.GetString("InvalidRefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to راند قرعه کشی صندوق مورد نظر معتبر نمی باشد ویا کد راند قرعه کشی اشتباه می باشد..
        /// </summary>
        public static string InvalidRound {
            get {
                return ResourceManager.GetString("InvalidRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تیکت مورد نظر وجود ندارد ویا کد ارسالی معتبر نمی باشد..
        /// </summary>
        public static string InvalidTicketId {
            get {
                return ResourceManager.GetString("InvalidTicketId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تراکنش معتبر نمی باشد.
        /// </summary>
        public static string InvalidTransactionId {
            get {
                return ResourceManager.GetString("InvalidTransactionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر مورد نظر پیدا نشد ویا کد ارسالی معتبر نمی باشد..
        /// </summary>
        public static string InvalidUserId {
            get {
                return ResourceManager.GetString("InvalidUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری یا رمز عبور اشتباه است.
        /// </summary>
        public static string InvalidUsernameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets/NotificationIcon/Draw.svg.
        /// </summary>
        public static string NotifyWinnerIconUrl {
            get {
                return ResourceManager.GetString("NotifyWinnerIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نتیجه قرعه کشی.
        /// </summary>
        public static string NotifyWinnerSubject {
            get {
                return ResourceManager.GetString("NotifyWinnerSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی 
        ///قرعه کشی {0} انجام شد
        ///کاربر {1} به عنوان برنده این قرعه کشی انتخاب شد.
        ///برای مشاهده نتیجه تمامی قرعه کشی ها به پنل خود مراجعه نمایید..
        /// </summary>
        public static string NotifyWinnerText {
            get {
                return ResourceManager.GetString("NotifyWinnerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد شانس های باقیمانده در این صندوق {0} عدد می باشد..
        /// </summary>
        public static string ParticipantCountOverflow {
            get {
                return ResourceManager.GetString("ParticipantCountOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets/NotificationIcon/PayBackIcon.png.
        /// </summary>
        public static string PayBackPurchaseIconUrl {
            get {
                return ResourceManager.GetString("PayBackPurchaseIconUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets/NotificationIcon/PayBackImage.png.
        /// </summary>
        public static string PayBackPurchaseImageUrl {
            get {
                return ResourceManager.GetString("PayBackPurchaseImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شارژ حساب کاربری.
        /// </summary>
        public static string PayBackSubject {
            get {
                return ResourceManager.GetString("PayBackSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی {0}
        ///حساب کاربری شما به مبلغ {1} تومان بابت محصول خریداری شده با نام {2} و عدم استفاده شانس های آن در قرعه کشی ها شارژ شد.
        ///مانده حساب کاربری شما : {3}.
        /// </summary>
        public static string PayBackText {
            get {
                return ResourceManager.GetString("PayBackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محصول خریداری شده برای کاربر جاری نمی باشد..
        /// </summary>
        public static string PuchaseNotForCurrentUser {
            get {
                return ResourceManager.GetString("PuchaseNotForCurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ مصرف استفاده از محصول خریداری شده تمام شده است..
        /// </summary>
        public static string PurchaseHasFinished {
            get {
                return ResourceManager.GetString("PurchaseHasFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محصول خریداری شده شانس استفاده نشده ای ندارد..
        /// </summary>
        public static string PurchaseNotAnyChanse {
            get {
                return ResourceManager.GetString("PurchaseNotAnyChanse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی
        ///محصول خریداری شده شما به دلیل استفاده از شانس های آن در قرعه کشی غیر قابل بازپرداخت می باشد..
        /// </summary>
        public static string PurchaseNotReFoundable {
            get {
                return ResourceManager.GetString("PurchaseNotReFoundable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دستگاهی برای ارسال پوش پیدا نشد.
        /// </summary>
        public static string PushSubscriberNotExist {
            get {
                return ResourceManager.GetString("PushSubscriberNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}مورد نظر یافت نشد.
        /// </summary>
        public static string RecordNotExist {
            get {
                return ResourceManager.GetString("RecordNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازیابی رمز عبور.
        /// </summary>
        public static string RecoverPassword {
            get {
                return ResourceManager.GetString("RecoverPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReFoundPurchase.
        /// </summary>
        public static string ReFoundPurchase {
            get {
                return ResourceManager.GetString("ReFoundPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرکت در قرعه کشی.
        /// </summary>
        public static string SpendChanceSubject {
            get {
                return ResourceManager.GetString("SpendChanceSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی
        ///شما در قرعه کشی سبد {0} شرکت کرده اید.
        ///شانس های قرعه کشی شما عبارتند از : 
        ///{1}.
        /// </summary>
        public static string SpendChanceText {
            get {
                return ResourceManager.GetString("SpendChanceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربری با این مشخصات قبلا ثبت نام کرده است..
        /// </summary>
        public static string SubscriptionAllReadyExist {
            get {
                return ResourceManager.GetString("SubscriptionAllReadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر مورد نظر وجود ندارد.
        /// </summary>
        public static string SubscriptionNotExist {
            get {
                return ResourceManager.GetString("SubscriptionNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات با موفقیت انجام شد..
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خرید محصول {0}.
        /// </summary>
        public static string SuccessPurchaseSubject {
            get {
                return ResourceManager.GetString("SuccessPurchaseSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی
        ///از خریدتان سپاسگذاریم.
        ///شما بابت خرید محصول {0} تعداد {1} عدد شانس برای شرکت در قرعه کشی دریافت کردید. 
        ///کد تخفیف : 
        ///{2}.
        /// </summary>
        public static string SuccessPurchaseText {
            get {
                return ResourceManager.GetString("SuccessPurchaseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این کد قبلا استفاده شده است و معتبر نمی باشد، لطفا مجدد تلاش کنید..
        /// </summary>
        public static string UsedPinCode {
            get {
                return ResourceManager.GetString("UsedPinCode", resourceCulture);
            }
        }
    }
}
